### PR TITLE
Popup modal, class input

### PR DESCRIPTION
**Pull request by iemxia**
Made the add task button populate a modal, overlay when clicked. Used the Modal component from React Bootstrap (see documentation [here](https://react-bootstrap.netlify.app/docs/components/modal)). Had to add a separate Form.css file to get the popup to work properly. Also changed the class input from select to input type: text and made it so that when it shows up on the card, the color is randomized using chroma.js (need to run  `npm install chroma-js`). Right now, itgenerates every time you reload page since its not stored anywhere, this may be something we want to change in the future. I made it so the text will always be the same shade as the background, just darker using `darkenColor` from chroma.js.

### CODE REVIEW

**Review by bellaboulais — APPROVED** [review]
Code looks good. I agree with comment that color of classes should be added to backend. Other than that, code is clean and simple, and good use of .css file for style options.

**Review by Crosa01 — APPROVED** [review]
Everything looks really good, my only comment is that when the background color generated is dark, it makes it a little hard to read, so potentially if you could change it so the background color would be within a certain brightness it would keep it clean and easy to read. Otherwise it looks great!

**Comment by iemxia** [comment]
> Everything looks really good, my only comment is that when the background color generated is dark, it makes it a little hard to read, so potentially if you could change it so the background color would be within a certain brightness it would keep it clean and easy to read. Otherwise it looks great!

Have added additional code so that the colors generated are not too dark.

**Review by eckester — APPROVED** [review]
Love the modal overlay, as well as the new style for the page, I think it adds a lot to the project. We will definitely need to go over the error where it regenerates when you reload, but as that is not as app breaking issue, we are absolutely good to go ahead and merge.

**Pull request merged**
